nomad_user: "root"
nomad_group: "root"

nomad_binary_version: "1.11.1"
nomad_binary_checksum: "sha256:a120ba1be96d536ef7196911b57bfbe78fe08c53935dfd16eae0206eba09d729"

nomad_config_dir: "/etc/nomad.d"
nomad_config_template: ""
nomad_data_dir: "/opt/nomad/data"

nomad_tls_enabled: false
nomad_tls_ca_cert: ""
nomad_tls_cert: ""
nomad_tls_cert_key: ""

nomad_license: ""

# The name of the systemd service to install for Nomad. This does not need to be
# changed often, but does allow running server and client agents on the same
# machine via separate services.
nomad_service_name: "nomad"
